### ISSUE TITLE
BUG: Add back master failed if svcsubnet modified

### ISSUE THREAD

**Issue by Deapou** [labring/sealos#2854] opened 2023-03-22 14:42 UTC
### Which command or component
sealos add --masters 192.168.138.142

### The Description of the bug
- error creating PKI assets
- failed to write or validate certificate "apiserver"
- certificate apiserver is invalid: x509
- certificate is valid for kubernetes.default.svc, kubernetes.default.svc.cluster.local, n2(192.168.138.142), localhost, kubernetes, kubernetes.default, not apiserver.cluster.local

### How to reproduce（pictures can be attached if necessary）
1.Install the cluster using Clusterfile:
```shell
apiVersion: apps.sealos.io/v1beta1
kind: Cluster
metadata:
  creationTimestamp: null
  name: default
spec:
  hosts:
  - ips:
    - 192.168.138.140:22
    - 192.168.138.141:22
    - 192.168.138.142:22
    roles:
    - master
    - amd64
  - ips:
    - 192.168.138.143:22
    - 192.168.138.144:22
    roles:
    - node
    - amd64
  image:
  - labring/kubernetes:v1.24.0
  - labring/calico:v3.22.1
  ssh:
    passwd: '[your-ssh-passwd]'
    pk: /root/.ssh/id_rsa
    port: 22
    user: root
status: {}
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  podSubnet: 172.16.0.0/12
  serviceSubnet: 192.168.0.0/16       
---
apiVersion: apps.sealos.io/v1beta1
kind: Config
metadata:
  name: calico
spec:
  path: manifests/calico.yaml
  data: |
    apiVersion: operator.tigera.io/v1
    kind: Installation
    metadata:
      name: default
    spec:
      calicoNetwork:
        ipPools:
        - blockSize: 26
          cidr: 172.16.0.0/12
          encapsulation: IPIP
          natOutgoing: Enabled
          nodeSelector: all()
        nodeAddressAutodetectionV4:
          interface: "eth.*|en.*"
```
2.use kubectl (Success)
```shell
root@master:~# kubectl get node
NAME     STATUS   ROLES           AGE   VERSION
master   Ready    control-plane   31h   v1.24.0
n1       Ready    control-plane   31h   v1.24.0
n2       Ready    control-plane   31h   v1.24.0
n3       Ready    <none>          31h   v1.24.0
n4       Ready    <none>          31h   v1.24.0
```

3.delete a master (Success)
```shell
sealos delete --masters 192.168.138.142 
```

4.use kubectl (Success)
```shell
root@master:~# kubectl get node
NAME     STATUS   ROLES           AGE   VERSION
master   Ready    control-plane   31h   v1.24.0
n1       Ready    control-plane   31h   v1.24.0
n3       Ready    <none>          31h   v1.24.0
n4       Ready    <none>          31h   v1.24.0
```
5.add back master (Failed)
```shell
sealos add --masters 192.168.138.142 
```

### What is the expected behavior?

add master success

### Operating environment

```markdown
- Sealos version:4.2.0-alpha1
- Docker version:none
- Kubernetes version:v1.24.0
- Operating system:ubuntu-server-20.0
- Runtime environment:containerd-v1.6.19
```

**Comment by bxy4543** [comment] 2023-03-23 09:41
wrong cert:
```
root@jh-node003:~# openssl x509 -in /etc/kubernetes/pki/apiserver.crt -noout -text | grep DNS
                DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:apiserver.cluster.local, DNS:kubernetes.default.svc.cluster.local, DNS:jh-node003, DNS:localhost, DNS:kubernetes, IP Address:172.30.27.20, IP Address:172.30.27.22, IP Address:172.30.27.21, IP Address:127.0.0.1, IP Address:10.96.0.1, IP Address:10.103.97.2
```
some logs: 
```
2023-03-23T17:19:46 debug start to exec remote 172.30.27.21:22 shell: /var/lib/sealos/data/default/rootfs/opt/sealctl  cert \
	 --node-ip 172.30.27.21 --node-name jh-node003 \
	 --service-cidr 10.96.0.0/22 --dns-domain cluster.local \
	 --alt-names 127.0.0.1  --alt-names apiserver.cluster.local  --alt-names 10.103.97.2  --alt-names 172.30.27.20  --alt-names 172.30.27.22  --alt-names 172.30.27.21 
172.30.27.21:22: 2023-03-23T17:19:47 info apiserver altNames : {map[apiserver.cluster.local:apiserver.cluster.local jh-node003:jh-node003 kubernetes:kubernetes kubernetes.default:kubernetes.default kubernetes.default.svc:kubernetes.default.svc kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local localhost:localhost] map[10.103.97.2:10.103.97.2 10.96.0.1:10.96.0.1 127.0.0.1:127.0.0.1 172.30.27.20:172.30.27.20 172.30.27.21:172.30.27.21 172.30.27.22:172.30.27.22]}

```

> I tested and found that when the service CIDR is modified to `172.30.0.0/16`, the join master will fail, because the wrong cert command is executed on the join master: `--service-cidr 10.96.0.0/22`

### GOOD FIRST ISSUE：
Handle the wrong serviceCIDR parameter here：
https://github.com/labring/sealos/blob/a02ebcafefbeb31b284ee8786987d7f7c6455721/pkg/runtime/runtime_getter.go#L158-L164
https://github.com/labring/sealos/blob/a02ebcafefbeb31b284ee8786987d7f7c6455721/pkg/runtime/master.go#L126

**Comment by cuisongliu** [comment] 2023-03-23 11:04
https://github.com/labring/sealos/issues/1623

**Comment by Deapou** [comment] 2023-04-03 06:16
```go
// MergeKubeadmConfig Unsafe, dangerous use of goroutines.
func (k *KubeadmRuntime) MergeKubeadmConfig() error {
	k.ImageKubeVersion = k.getKubeVersionFromImage()
	for _, fn := range []string{
		"",                          // generate default kubeadm configs
		k.getDefaultKubeadmConfig(), // merging from predefined path of file if file exists
	} {
		if err := k.Merge(fn); err != nil {
			return err
		}
	}
	// merge from clusterfile
	if k.Config.ClusterFileKubeConfig != nil {
		if err := k.LoadFromClusterfile(k.Config.ClusterFileKubeConfig); err != nil {
			return fmt.Errorf("failed to load kubeadm config from clusterfile: %v", err)
		}
	}
	k.setKubeadmAPIVersion()
	return k.validateVIP(k.getVip())
}
``` 
According to the hint given by the boss, I tested the function **MergeKubeadmConfig**. The first part is OK (merge two configuration files with **merge**), and I guess the problem occurs in the second part (secondary overwriting of cluster configuration), but this part is not good for testing, is this idea correct?

**Comment by bxy4543** [comment] 2023-04-03 07:11
@Deapou 
I think the problem is here: https://github.com/labring/sealos/blob/a929e01b639a409d03c9db06694f9a01e0fcb936/pkg/runtime/kubeadm.go#L122

Because ClusterConfiguration (including serviceSubnet configuration) is saved under ${HOME}/.sealos/default/etc/kubeadm-init.yaml, but this file is not merged here, and we cannot get the correct serviceSubnet

```
root@jh-node001:~/tigera-operator# cat /root/.sealos/default/etc/kubeadm-init.yaml | grep serviceSubnet
   serviceSubnet: 10.96.0.0/22
root@jh-node001:~/tigera-operator# ssh 172.30.27.22 cat /root/.sealos/default/etc/kubeadm-join-node.yaml | grep serviceSubnet
```

**Comment by Deapou** [comment] 2023-04-03 11:20
@bxy4543 
```go
func TestAdd(t *testing.T) {
	k := new(KubeadmRuntime)
	t.Log(k.getDefaultKubeadmConfig())
}
``` 
I test the function **getDefaultKubeadmConfig** and indeed I get a different path than ${HOME}/.sealos/default/etc/kubeadm-init.yaml.
```shell
PS D:\go\project\sealos\test\modifyT> go test -v
=== RUN   TestAdd
    r_test.go:23: data\ClusterName\rootfs\etc\kubeadm.yml
--- PASS: TestAdd (0.00s)
PASS
ok      github.com/labring/sealos/test/modifyT  0.264s
```

**Comment by bxy4543** [comment] 2023-04-06 02:59
@Deapou 
Because this directory `data/ClusterName/rootfs/etc/kubeadm.yml` is in the build cluster rootfs image custom kubeadm configuration can be overwritten by other configurations, such as the kubeadm configuration in the Clusterfile

**Closed** 2023-04-13 12:48 UTC
Labels: kind/bug, good first issue
